import "antd/dist/reset.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TrainerProvider } from "./providers/Registration/provider";
import { LoginProvider } from "./providers/Login/provider";
import { UserProvider } from "./providers/currentUser/provider";
import { ClientProvider } from "./providers/createclient/provider";
import { ClientRegistrationProvider } from "./providers/clientregistration/provider";
import { ClientLoginProvider } from "./providers/ClientLogin/provider";
import { fetchTrainerClients } from "./providers/GetClientsForTrainer/provider";
import FoodProvider from "./providers/GetFoodItems/providers";
import { FoodItemsProvider } from "./providers/FoodItems/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TrainerProvider>
          <LoginProvider>
            <UserProvider>
              <ClientProvider>
                <ClientRegistrationProvider>
                  <ClientLoginProvider>
                    <FoodProvider>
                      <FoodItemsProvider>{children}</FoodItemsProvider>
                    </FoodProvider>
                  </ClientLoginProvider>
                </ClientRegistrationProvider>
              </ClientProvider>
            </UserProvider>
          </LoginProvider>
        </TrainerProvider>
      </body>
    </html>
  );
}
